name: Publish ZIP

on:
  release:
    types: [published]

jobs:
  publish-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1️⃣ Checkout del repo completo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Instalar Node.js y dependencias (por si necesitamos rebuild)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # 3️⃣ Crear estructura de carpetas para HACS
      - name: Prepare HACS folder structure
        run: |
          rm -rf tmp
          mkdir -p tmp/meteocat-card
          cp dist/meteocat-card.js tmp/meteocat-card/
          cp src/meteocat-card-editor.js tmp/meteocat-card/
          cp src/loader.js tmp/meteocat-card/
          cp -r icons tmp/meteocat-card/

      # 4️⃣ Crear ZIP final con la estructura que HACS espera
      - name: Create ZIP
        run: |
          cd tmp
          zip -r ../meteocat-card.zip meteocat-card
          cd ..
          echo "ZIP created at $PWD/meteocat-card.zip"

      # 5️⃣ Subir el ZIP como asset al release
      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: meteocat-card.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
