name: Build & Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout completo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # Configurar Git author para semantic-release
      - name: Configure Git author
        run: |
          git config user.name "semantic-release-bot"
          git config user.email "jdcuartero@yahoo.es"

      # Ejecutar semantic-release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Build del bundle
      - name: Build meteocat-card.js
        run: npm run build

      # Subir todos los archivos compilados al release
      - name: Upload bundle to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*,hacs.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
