name: Publish ZIP

on:
  release:
    types: [created, published]

jobs:
  publish-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1️⃣ Checkout completo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Construir los archivos dist
      - name: Build bundle
        run: npm run build

      # 5️⃣ Crear estructura de carpetas HACS
      - name: Prepare HACS folder structure
        run: |
          rm -rf tmp
          mkdir -p tmp/meteocat-card
          cp dist/meteocat-card.js tmp/meteocat-card/
          cp dist/meteocat-card-editor.js tmp/meteocat-card/
          cp -r icons tmp/meteocat-card/
          cp hacs.json tmp/meteocat-card/

      # 6️⃣ Crear ZIP final
      - name: Create ZIP
        run: |
          cd tmp
          zip -r ../meteocat-card.zip meteocat-card
          cd ..
          echo "ZIP created at $PWD/meteocat-card.zip"

      # 7️⃣ Subir ZIP como asset al release creado
      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: meteocat-card.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
