name: Build & Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout completo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Configurar Git author para semantic-release
      - name: Configure Git author
        run: |
          git config user.name "semantic-release-bot"
          git config user.email "jdcuartero@yahoo.es"

      # 5️⃣ Ejecutar semantic-release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # 6️⃣ Build del bundle
      - name: Build meteocat-card.js
        run: npm run build
