name: Build & Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout completo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Configurar Git author
      - name: Configure Git author
        run: |
          git config user.name "semantic-release-bot"
          git config user.email "jdcuartero@yahoo.es"

      # 5️⃣ Ejecutar semantic-release y obtener la nueva versión
      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
          # Guardamos la versión recién publicada en un archivo temporal
          echo "VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | awk '{print $NF}')" >> $GITHUB_ENV

      # 6️⃣ Build del bundle
      - name: Build meteocat-card.js
        run: npm run build

      # 7️⃣ Crear ZIP para HACS
      - name: Prepare HACS ZIP
        run: |
          rm -rf tmp
          mkdir -p tmp/meteocat-card
          cp dist/meteocat-card.js tmp/meteocat-card/
          cp dist/meteocat-card-editor.js tmp/meteocat-card/
          cp -r icons tmp/meteocat-card/
          cp hacs.json tmp/meteocat-card/
          cd tmp
          zip -r ../meteocat-card.zip meteocat-card
          cd ..
          echo "ZIP created at $PWD/meteocat-card.zip"

      # 8️⃣ Subir ZIP al release recién creado
      - name: Upload ZIP to release
        run: |
          echo "Uploading ZIP to release v$VERSION"
          gh release upload "v$VERSION" meteocat-card.zip --repo $GITHUB_REPOSITORY --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
